workspace = { members = ["net/wasabi", "saba_core", "ui/wasabi"] }

[package]
name = "saba"
version = "0.1.0"
edition = "2021"
default-run = "saba"

[[bin]]
name = "saba"
path = "./src/main.rs"
required-features = ["wasabi"]

[dependencies]
net_wasabi = { path = "./net/wasabi", optional = true }
noli = { git = "https://github.com/hikalium/wasabi.git", branch = "for_saba", optional = true }
saba_core = { path = "./saba_core" }
ui_wasabi = { path = "./ui/wasabi", optional = true }

[features]
default = ["wasabi"]
wasabi = ["dep:net_wasabi", "dep:noli", "dep:ui_wasabi"]
